FROM 2m0sql/cloudlog:latest

ENV LOCATOR set_me
ENV BASE_URL set_me

ENV CALLBOOK set_me
ENV CALLBOOK_USERNAME set_me
ENV CALLBOOK_PASSWORD set_me

ENV DATABASE_HOSTNAME set_me
ENV DATABASE_NAME set_me
ENV DATABASE_USERNAME set_me
ENV DATABASE_PASSWORD set_me

ENV DEVELOPER_MODE set_me
ENV DATABASE_IS_MARIADB set_me
ENV CLOUDLOG_LOGGING set_me

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apachectl", "-D", "FOREGROUND"]
