name: Build image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Latest version of Cloudlog to build'
        required: true

jobs:
  build_and_push:
    name: Build and push Cloudlog Docker image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: RELEASE_VERSION=${{ github.event.inputs.release_version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            neilbartley/cloudlog:latest
            neilbartley/cloudlog:${{ github.event.inputs.release_version }}
            ghcr.io/neilbartley/cloudlog:latest
            ghcr.io/neilbartley/cloudlog:${{ github.event.inputs.release_version }}
